### ISSUE TITLE
Not support for Chinese

### ISSUE THREAD

**Issue by SivilTaram** [chenjianjx/wechat-encrypt-python3#1]
您好，我在微信公众号的开发中用到了您python3版本的微信加密程序，首先对您表示感谢！

目前有一个问题在于，如果传输的是中文，在微信中将会显示为`\xe82`这种`unicode`格式，我在仔细debug后认为这是由python3的加密库只能对unicode加密 ，而微信端认为该unicode是utf8来解码导致的。不知道您是否遇到了这种问题，有什么好的解决思路吗？

再次感谢您的工作:)

**Comment by chenjianjx** [comment]
My Django's code which handles http requests from wechat-server: 

````python

    wechat_decrypt = WXBizMsgCrypt(...)
    
   if request.method == 'POST':
        xml = request.body.decode("utf8")
        ret, xml = wechat_decrypt.DecryptMsg(xml, msg_sign, timestamp, nonce)
        ...
       
        ret, resp_xml  =   wechat_decrypt.EncryptMsg(some_clear_xml, nonce)
        return HttpResponse(resp_xml)
                                        

````

**Comment by SivilTaram** [comment]
我理解您的意思，我想可能是我说的有些模糊让您误解了。

我这里出现错误不是在服务器收到的wechat消息格式，主要是在服务器响应的发送给用户的消息。

比如用户输入一个字符串，服务器被动响应，如果我没理解错的话，在Python3中服务器只能对unicode加密，加密后将其放入xml_data传输给微信服务器，微信服务器解密后会默认它是一个utf8的字符串，所以出现了`\xe82`这种格式。

我理解的是否有误？恳请指正，谢谢:)

**Comment by chenjianjx** [comment]
Don't know, Sir.  Please work that out by yourself.
